version: '3'

services:
  czech_backend:
    image: czech_backend
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - czech-mysql
    volumes:
      - /app/czech:/app

  czech-frontend:
    image: czech-frontend
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - czech_backend
    volumes:
      - /app/czech:/app

  czech-mysql:
    image: percona/percona-server:5.7
    ports:
      - 3367:3306
    environment:
      MYSQL_DATABASE: czech
      MYSQL_USER: czech
      MYSQL_PASSWORD: 12341234
      MYSQL_ROOT_PASSWORD: 12341234
      MYSQL_RANDOM_ROOT_PASSWORD: 12341234
    volumes:
      - /app/mysql/czech-mysql:/var/lib/mysql
